apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-microservice
  labels:
    app: my-microservice
  annotations:
    source: base-manifest-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-microservice
  template:
    metadata:
      labels:
        app: my-microservice
    spec:
      serviceAccountName: my-microservice
      volumes:
        - name: secret-vol
          secret:
            secretName: my-microservice-secret0
      containers:
        - name: my-microservice
          ports:
          - containerPort: 80
            protocol: TCP
          volumeMounts:
          - name: secret-vol
            readOnly: true
            mountPath: /etc/secret-vol
          env:
          - name: TEST_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: my-microservice-secret1
                key: secret1
          - name: TEST_CONFIGMAP_KEY
            valueFrom:
              configMapKeyRef:
                name: my-microservice-config
                key: TEST_CONFIGMAP
---
apiVersion: v1
kind: Service
metadata:
  name: my-microservice
  annotations:
    source: base-manifest-test
spec:
  selector:
    app.kubernetes.io/name: my-microservice
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-microservice
  annotations:
    source: base-manifest-test
---