name: Issues Automation

on:
  issues:
    types: [opened, edited, deleted, closed, reopened, labeled, unlabeled, assigned]

concurrency:
  group: issue-${{ github.event.issue.number }}
  cancel-in-progress: false

permissions:
  id-token: write # Required for requesting the JWT
  issues: write # Required for updating the issue

jobs:
  ado:
    name: Sync issue to Azure DevOps
    runs-on: ubuntu-latest
    environment:
      name: issues
    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_SP_TESTS_APPID }}
          tenant-id: ${{ secrets.AZURE_SP_TESTS_TENANTID }}
          subscription-id: ${{ vars.ENV_APPSERVICE_SUBSCRIPTIONID }}
      - name: Get Azure DevOps token
        id: get_ado_token
        run:
          # The resource ID for Azure DevOps is always 499b84ac-1321-427f-aa17-267ca6975798
          # https://learn.microsoft.com/azure/devops/integrate/get-started/authentication/service-principal-managed-identity
          $accessToken = az account get-access-token --resource 499b84ac-1321-427f-aa17-267ca6975798 --query "accessToken" --output tsv
          echo "##[set-output name=ado_token;]$accessToken"
      - name: Sync issue to Azure DevOps
        uses: danhellem/github-actions-issue-to-work-item@v2.2
        env:
          ado_token: "${{ steps.get_ado_token.outputs.ado_token }}"
          github_token: "${{ secrets.GH_RAD_CI_BOT_PAT }}"
          ado_organization: "azure-octo"
          ado_project: "Incubations"
          ado_area_path: "Incubations\\Radius"
          ado_iteration_path: "Incubations\\Radius"
          ado_new_state: "New"
          ado_active_state: "Active"
          ado_close_state: "Closed"
          ado_wit: "GitHub Issue"
